print("Домашнее задание №12. Строка и срезы")
str1 = input("Введите строку:")
print("a)", str1[2] )
print("b)", str1[-2] )
print("c)", str1[:5] )
print("d)", str1[:-2] )
print("e)", str1[::2] )
print("f)", str1[1::2] )
print("g)", str1[::-1] )
print("h)", str1[::-2] )
print("i)", len(str1) )